# Ups local test environment.

version: '3'
services:

  test-postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    command: postgres -c max_connections=300 -c log_min_messages=NOTICE
    environment:
      - POSTGRES_PASSWORD=leshiy
    volumes:
      - /tmp/test-postgres:/var/lib/postgresql/data

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  192.168.56.0/16
